### ISSUE TITLE
:emptyのスタイルについて

### ISSUE THREAD

**Issue by monosus-matsunaga** [monoharada/axe-dev-tooltip#1]
@monoharada 

「Show accessibility problems」ボタンをONにした時、空のbuttonタグが横に伸びきっていましたので報告です。

「Show accessibility problems」ボタンをOFF時
![スクリーンショット 2024-07-12 20 20 32](https://github.com/user-attachments/assets/588de3d2-b18e-4eec-8252-57bd872c2600)

「Show accessibility problems」ボタンをON時
![スクリーンショット 2024-07-12 20 20 51](https://github.com/user-attachments/assets/744b70d3-8c4d-4631-8ffa-a7016fb9c9ab)

個人的にこうあって欲しい
![スクリーンショット 2024-07-12 20 21 55](https://github.com/user-attachments/assets/f381e54f-d157-407a-bbd8-5f12fe500c47)

## 該当のソースコード
https://github.com/monoharada/axe-dev-tooltip/blob/542dc6c48dec0113a419df7bb218e41bfe41f9c4/src/index.ts#L43-L47

以下のコードが原因みたいです。
どのような理由で入れてますでしょうか。
```
min-width: 90%;
min-height: 20px;
```

## 補足
ちなみにnext.jsのblog-starter-appで試しました。

**Comment by monoharada** [comment]
@monosus-matsunaga 
あざます！
これは:emptyの考え方がだめでしたね。
要素が空で要素の大きさがない場合はツールチップを表示するためにマウスオーバー領域を確保する。

要素が空でも大きさを取得できる場合はそのままでボーダーで囲う

という分岐を追加します！

**Comment by monosus-matsunaga** [comment]
@monoharada 
確認ありがとうございます。
ツールチップ要素の確保あれば、min-width: 90%; => 20pxで良い気がしました。
こういう修正って、ブランチきってプルリク出しても良いのでしょうか。

**Comment by monoharada** [comment]
@monosus-matsunaga 
そうですね
修正いただけるとありがたいです！
まだリファクタリングしていないため煩雑なコードになっていますが…

**Comment by monoharada** [comment]
@monosus-matsunaga 
コラボレーター追加しました

**Comment by monoharada** [comment]
@monosus-matsunaga 
修正方法IMOですが
要素の大きさを取得して横幅*高さが0だったら切り分けるクラスを付与して、そのクラス+:empty+もろもろのdata属性がついていたら要素を視認出来るように大きくするスタイルを当てるとかかなと思いました。

(20pxだとホバーがつらそう）

**Comment by monoharada** [comment]
@monosus-matsunaga 
これ対応しちゃいます！

**Comment by monosus-matsunaga** [comment]
@monoharada 
提案しておきながら亀レスですみません！

> 要素の大きさを取得して横幅*高さが0だったら切り分けるクラスを付与
自分がやろうとしていたのはmin-widthをつけることだけでしたが、そのようが良い気がします。
確かに20px x 20pxだと小さすぎますもんね。

どうしよう、無駄かもですが、自分でも書いてみます。

**Comment by monosus-matsunaga** [comment]
@monoharada 

と思ったら、今修正いただきましたね。
改めてつかってみます。

**Comment by monoharada** [comment]
はい
@monosus-matsunaga 
0.0.7で試してみてください。
<img width="999" alt="SCR-20240716-ppfy" src="https://github.com/user-attachments/assets/df7b8777-37fa-4172-a2ab-52da96a0a26f">
手元では良さそうです。

次回からPRだします！

**Comment by monosus-matsunaga** [comment]
@monoharada 

0.0.8が出てましたのでそちらで確認しました。
確認できました。
また、何か見つけたらissue出そうかと思います。

これでcloseします。
